-- INITIAL SETUP ONLY: run once in an empty Supabase project.
-- Generated with npm run setup:sql. Do not run alongside the individual migrations.
begin;

-- supabase/migrations/202609070001_platform.sql
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create table public.profiles(id uuid primary key references auth.users on delete cascade,full_name text not null default '',email text not null default '',organization text not null default '',participant_role text not null default 'Guest',grade text,role text not null default 'USER' check(role in ('USER','PARTICIPANT','GUEST','SPEAKER','PARTNER','ORGANIZER','ADMIN')),created_at timestamptz not null default now());
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role in ('ADMIN','ORGANIZER'))$$;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='ADMIN')$$;
create function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,email) values(new.id,coalesce(new.email,''));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.new_profile();
create table applications(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references profiles,status text not null default 'PENDING' check(status in ('PENDING','APPROVED','WAITLIST','REJECTED')),consent_at timestamptz not null default now(),created_at timestamptz not null default now());
create table promo_codes(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null default '',type text not null default 'GENERAL' check(type in ('GENERAL','GUEST','PARTICIPANT','STARTUP_BATTLE','HACKATHON','JAS_STARTUPER','FIFA','SPEAKER','PARTNER','ORGANIZER','VIP_GUEST')),max_uses integer not null default 1 check(max_uses>0),used_count integer not null default 0,expires_at timestamptz,active boolean not null default true,notes text,created_at timestamptz not null default now());
create table promo_code_redemptions(id uuid primary key default gen_random_uuid(),promo_code_id uuid not null references promo_codes,user_id uuid not null references profiles,created_at timestamptz not null default now(),unique(promo_code_id,user_id));
create table tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references profiles,token text not null unique default encode(extensions.gen_random_bytes(32),'hex'),type text not null default 'GENERAL',status text not null default 'ACTIVE' check(status in ('ACTIVE','REVOKED')),checked_in_at timestamptz,created_at timestamptz not null default now());
create table speakers(id uuid primary key default gen_random_uuid(),secret boolean not null default true,kind text not null default 'KEYNOTE' check(kind in ('KEYNOTE','PANELIST')),name text not null default 'SECRET SPEAKER',position text not null default '',company text not null default '',photo text,bio text,topic text default 'TOPIC TO BE REVEALED',session text,social jsonb not null default '{}',sort_order integer not null default 0);
create table events(id uuid primary key default gen_random_uuid(),title text not null,description text not null default '',day integer not null check(day between 12 and 19),time text not null default 'TBA',track text not null,location text not null default 'Venue TBA',speaker_id uuid references speakers,capacity integer check(capacity>0),registration_required boolean not null default true,coins integer not null default 0 check(coins>=0),published boolean not null default true);
create table event_registrations(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,event_id uuid not null references events,status text not null check(status in ('REGISTERED','WAITLIST','ATTENDED')),created_at timestamptz not null default now(),unique(user_id,event_id));
create table attendance(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,event_id uuid not null references events,scanned_by uuid not null references profiles,coins_awarded integer not null default 0,created_at timestamptz not null default now(),unique(user_id,event_id));
create table ticket_scans(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references tickets,event_id uuid references events,scanned_by uuid not null references profiles,result text not null,created_at timestamptz not null default now());
create table questions(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,body text not null check(length(body) between 10 and 1000),status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED','HIGHLIGHTED')),created_at timestamptz not null default now());
create table competitions(id uuid primary key default gen_random_uuid(),slug text not null unique,title text not null,description text not null default '',rules text not null default 'Rules to be announced.',judging text not null default 'Judging criteria to be announced.',published boolean not null default false,bracket jsonb not null default '[]');
create table teams(id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid not null references profiles,members jsonb not null default '[]');
create table competition_entries(id uuid primary key default gen_random_uuid(),competition_id uuid not null references competitions,user_id uuid not null references profiles,team_id uuid references teams,name text not null,description text not null default '',logo text,founders text,category text,website text,pitch_time text,status text not null default 'APPLICATION' check(status in ('APPLICATION','REVIEW','FINALIST','FINAL','WINNER','REJECTED')),place integer check(place>0),created_at timestamptz not null default now(),unique(competition_id,user_id));
create table zones(id uuid primary key default gen_random_uuid(),name text not null,description text not null default '',icon text,sort_order integer not null default 0);
create table partners(id uuid primary key default gen_random_uuid(),name text not null,logo text,website text,type text not null check(type in ('ORGANIZER','GENERAL PARTNER','PARTNER','TECH PARTNER','COMMUNITY PARTNER','MEDIA PARTNER')));
create table coin_rules(id uuid primary key default gen_random_uuid(),key text not null unique,name text not null,points integer not null check(points>=0),active boolean not null default true);
create table coin_transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,amount integer not null check(amount<>0),reason text not null check(length(reason)>2),source_key text not null,admin_id uuid references profiles,created_at timestamptz not null default now(),unique(user_id,source_key));
create table achievements(id uuid primary key default gen_random_uuid(),key text not null unique,name text not null,description text not null);
create table user_achievements(user_id uuid references profiles,achievement_id uuid references achievements,created_at timestamptz not null default now(),primary key(user_id,achievement_id));
create table certificates(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references profiles,recipient_name text not null,status text not null default 'ISSUED' check(status in ('ISSUED','REVOKED')),created_at timestamptz not null default now());
create table admin_logs(id uuid primary key default gen_random_uuid(),admin_id uuid references profiles,action text not null,entity text,entity_id text,details jsonb,created_at timestamptz not null default now());
create table site_settings(key text primary key,value jsonb not null);
create table rate_limits(user_id uuid references profiles,action text,window_start timestamptz not null default now(),attempts integer not null default 0,primary key(user_id,action));
create index on attendance(event_id);create index on coin_transactions(user_id,created_at);create index on event_registrations(event_id,status);create index on applications(created_at);create index on ticket_scans(ticket_id);
-- All tables default-deny; only explicit policies grant access.
do $$declare t text;begin foreach t in array array['profiles','applications','promo_codes','promo_code_redemptions','tickets','speakers','events','event_registrations','attendance','ticket_scans','questions','competitions','teams','competition_entries','zones','partners','coin_rules','coin_transactions','achievements','user_achievements','certificates','admin_logs','site_settings','rate_limits'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy own_profile on profiles for select to authenticated using(id=auth.uid() or is_staff());
create policy own_application on applications for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_ticket on tickets for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_redemption on promo_code_redemptions for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_registration on event_registrations for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_attendance on attendance for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_coins on coin_transactions for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_certificate on certificates for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_achievements on user_achievements for select to authenticated using(user_id=auth.uid() or is_staff());
create policy own_questions on questions for select to authenticated using(user_id=auth.uid() or is_staff());
create policy send_question on questions for insert to authenticated with check(user_id=auth.uid() and status='PENDING');
create policy manage_questions on questions for update to authenticated using(is_staff()) with check(is_staff());
create policy own_teams on teams for select to authenticated using(owner_id=auth.uid() or is_staff());
create policy own_entries on competition_entries for select using(user_id=auth.uid() or is_staff() or (status in ('FINALIST','FINAL','WINNER') and exists(select 1 from competitions c where c.id=competition_id and c.published)));
create policy enter_competition on competition_entries for insert to authenticated with check(user_id=auth.uid() and status='APPLICATION' and place is null);
-- Secret identities are never readable by anonymous/ordinary users, even via the REST API.
create policy public_speakers on speakers for select using(not secret or is_staff());
create policy public_events on events for select using(published or is_staff());
do $$declare t text;begin foreach t in array array['competitions','zones','partners','coin_rules','achievements','site_settings'] loop execute format('create policy public_read on %I for select using(true)',t);end loop;foreach t in array array['speakers','events','competitions','competition_entries','zones','partners','coin_rules','achievements','site_settings','promo_codes'] loop execute format('create policy staff_manage on %I for all to authenticated using(is_staff()) with check(is_staff())',t);end loop;foreach t in array array['admin_logs','ticket_scans'] loop execute format('create policy staff_read on %I for select to authenticated using(is_staff())',t);end loop;end$$;
create function public.audit_change() returns trigger language plpgsql security definer set search_path=public as $$begin insert into admin_logs(admin_id,action,entity,entity_id,details) values(auth.uid(),tg_op,tg_table_name,coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id',to_jsonb(new)->>'key'),jsonb_build_object('old',to_jsonb(old),'new',to_jsonb(new)));if tg_op='DELETE' then return old;end if;return new;end$$;
do $$declare t text;begin foreach t in array array['applications','promo_codes','tickets','events','speakers','competitions','competition_entries','coin_rules','coin_transactions','certificates','site_settings','zones','partners','questions'] loop execute format('create trigger audit after insert or update or delete on %I for each row execute function audit_change()',t);end loop;end$$;
create function public.sync_rewards(uid uuid) returns void language plpgsql security definer set search_path=public as $$declare balance integer; target integer;begin select coalesce(sum(amount),0) into balance from coin_transactions where user_id=uid;select coalesce((value::text)::integer,400) into target from site_settings where key='certificateThreshold';target:=coalesce(target,400);
if balance>=target then insert into certificates(user_id,recipient_name) select id,full_name from profiles where id=uid on conflict(user_id) do nothing;end if;
insert into user_achievements(user_id,achievement_id) select uid,id from achievements where (key='FIRST_STEP' and exists(select 1 from applications where user_id=uid)) or (key='DIGITAL_EXPLORER' and (select count(*) from attendance where user_id=uid)>=3) or (key='BUILDER' and exists(select 1 from attendance a join events e on e.id=a.event_id where a.user_id=uid and e.track in ('WORKSHOPS','3D','HACKATHON'))) or (key='NETWORKER' and exists(select 1 from attendance a join events e on e.id=a.event_id where a.user_id=uid and e.title='Panel Discussion')) or (key='STARTUP_MIND' and exists(select 1 from attendance a join events e on e.id=a.event_id where a.user_id=uid and e.title like 'Startup Battle%')) or (key='DIGITAL_MASTER' and balance>=target) on conflict do nothing;end$$;
create function public.award(uid uuid,points integer,why text,source text) returns void language plpgsql security definer set search_path=public as $$begin if points<>0 then insert into coin_transactions(user_id,amount,reason,source_key,admin_id) values(uid,points,why,source,auth.uid()) on conflict(user_id,source_key) do nothing;end if;perform sync_rewards(uid);end$$;
create function public.apply_forum(full_name_input text,organization_input text,participant_role_input text,grade_input text default null) returns jsonb language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();begin if uid is null then raise exception 'Sign in first';end if;if length(trim(full_name_input))<2 or length(full_name_input)>120 or length(organization_input)>180 or participant_role_input not in ('Student','Teacher','Startup Founder','Developer','Guest','Partner','Other') then raise exception 'Invalid application';end if;if exists(select 1 from site_settings where key='registrationEnabled' and value='false') then raise exception 'Applications are closed';end if;update profiles set full_name=trim(full_name_input),organization=organization_input,participant_role=participant_role_input,grade=left(grade_input,30) where id=uid;insert into applications(user_id) values(uid) on conflict(user_id) do nothing;perform award(uid,coalesce((select points from coin_rules where key='registration' and active),0),'Forum registration','registration');return jsonb_build_object('message','APPLICATION RECEIVED');end$$;
create function public.review_application(application_id uuid,new_status text) returns jsonb language plpgsql security definer set search_path=public as $$declare uid uuid;begin if not is_staff() then raise exception 'Forbidden';end if;if new_status not in ('APPROVED','WAITLIST','REJECTED') then raise exception 'Invalid status';end if;update applications set status=new_status where id=application_id returning user_id into uid;if uid is null then raise exception 'Application not found';end if;if new_status='APPROVED' then insert into tickets(user_id) values(uid) on conflict(user_id) do nothing;end if;return jsonb_build_object('message',new_status);end$$;
create function public.activate_promo(invitation_code text) returns jsonb language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid(); p promo_codes; limiter rate_limits;begin if uid is null then raise exception 'Sign in first';end if;insert into rate_limits(user_id,action,attempts) values(uid,'promo',0) on conflict do nothing;select * into limiter from rate_limits where user_id=uid and action='promo' for update;if limiter.window_start<now()-interval '15 minutes' then update rate_limits set attempts=0,window_start=now() where user_id=uid and action='promo';limiter.attempts:=0;end if;if limiter.attempts>=5 then return jsonb_build_object('error','Too many attempts. Try again in 15 minutes.');end if;update rate_limits set attempts=attempts+1 where user_id=uid and action='promo';
if not exists(select 1 from profiles where id=uid and length(full_name)>1) then return jsonb_build_object('error','Complete your application details first.');end if;
select * into p from promo_codes where code=upper(trim(invitation_code)) for update;if p.id is null or not p.active or p.used_count>=p.max_uses or p.expires_at<=now() then return jsonb_build_object('error','Invitation code is invalid, expired or fully used.');end if;if exists(select 1 from promo_code_redemptions where promo_code_id=p.id and user_id=uid) then return jsonb_build_object('error','You have already activated this code.');end if;if exists(select 1 from tickets where user_id=uid) then return jsonb_build_object('error','You already have a pass. Contact an organizer for changes.');end if;insert into promo_code_redemptions(promo_code_id,user_id) values(p.id,uid);update promo_codes set used_count=used_count+1 where id=p.id;insert into tickets(user_id,type) values(uid,p.type);update applications set status='APPROVED' where user_id=uid;return jsonb_build_object('message','ACCESS GRANTED · Your Digital Pass is ready.');end$$;
create function public.register_event(event_id_input uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();e events;s text;begin if uid is null then raise exception 'Sign in first';end if;if not exists(select 1 from tickets where user_id=uid and status='ACTIVE') then raise exception 'An active Digital Pass is required';end if;select * into e from events where id=event_id_input and published for update;if e.id is null then raise exception 'Event not found';end if;select status into s from event_registrations where user_id=uid and event_id=e.id;if s is not null then return jsonb_build_object('message',s);end if;s:='REGISTERED';if e.capacity is not null and (select count(*) from event_registrations where event_id=e.id and status in ('REGISTERED','ATTENDED'))>=e.capacity then s:='WAITLIST';end if;insert into event_registrations(user_id,event_id,status) values(uid,e.id,s);return jsonb_build_object('message',case when s='WAITLIST' then 'Added to the waitlist' else 'Added to your schedule' end);end$$;
create function public.inspect_ticket(ticket_token text) returns jsonb language plpgsql security definer set search_path=public as $$declare t tickets;p profiles;begin if not is_staff() then raise exception 'Forbidden';end if;select * into t from tickets where token=ticket_token;if t.id is null or t.status<>'ACTIVE' then return jsonb_build_object('valid',false,'message','INVALID PASS');end if;select * into p from profiles where id=t.user_id;return jsonb_build_object('valid',true,'name',p.full_name,'role',p.participant_role,'type',t.type,'checked_in_at',t.checked_in_at,'message',case when t.checked_in_at is null then 'VALID PASS' else 'ALREADY CHECKED IN' end);end$$;
create function public.scan_ticket(ticket_token text,event_id_input uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$declare t tickets;e events;points integer;begin if not is_staff() then raise exception 'Forbidden';end if;select * into t from tickets where token=ticket_token for update;if t.id is null or t.status<>'ACTIVE' then return jsonb_build_object('error','INVALID PASS');end if;if event_id_input is null then if t.checked_in_at is not null then return jsonb_build_object('message','ALREADY CHECKED IN','time',t.checked_in_at);end if;update tickets set checked_in_at=now() where id=t.id;points:=coalesce((select r.points from coin_rules r where key='check_in' and active),0);perform award(t.user_id,points,'Forum check-in','check_in');else
select * into e from events where id=event_id_input;if e.id is null then raise exception 'Event not found';end if;if exists(select 1 from attendance where user_id=t.user_id and event_id=e.id) then return jsonb_build_object('message','ALREADY ATTENDED');end if;
points:=e.coins;insert into attendance(user_id,event_id,scanned_by,coins_awarded) values(t.user_id,e.id,auth.uid(),points);insert into event_registrations(user_id,event_id,status) values(t.user_id,e.id,'ATTENDED') on conflict(user_id,event_id) do update set status='ATTENDED';perform award(t.user_id,points,e.title,'event:'||e.id::text);end if;
insert into ticket_scans(ticket_id,event_id,scanned_by,result) values(t.id,event_id_input,auth.uid(),'VALID');return jsonb_build_object('message','CHECKED IN','coins',points,'time',now());end$$;
create function public.adjust_coins(user_id_input uuid,amount_input integer,reason_input text) returns jsonb language plpgsql security definer set search_path=public as $$begin if not is_staff() then raise exception 'Forbidden';end if;if amount_input=0 or abs(amount_input)>10000 or length(trim(reason_input))<3 then raise exception 'Enter an amount and a reason';end if;perform award(user_id_input,amount_input,trim(reason_input),'manual:'||gen_random_uuid());return jsonb_build_object('message','Coin adjustment recorded');end$$;
create function public.generate_promos(count_input integer,type_input text,max_uses_input integer default 1) returns jsonb language plpgsql security definer set search_path=public as $$begin if not is_staff() then raise exception 'Forbidden';end if;if count_input not between 1 and 500 or max_uses_input not between 1 and 10000 then raise exception 'Invalid limits';end if;insert into promo_codes(code,type,max_uses,name) select 'DNF-'||upper(encode(extensions.gen_random_bytes(4),'hex'))||'-'||upper(encode(extensions.gen_random_bytes(4),'hex')),type_input,max_uses_input,'Generated invitation' from generate_series(1,count_input);return jsonb_build_object('message',count_input||' invitation codes created');end$$;
create function public.manage_ticket(ticket_id_input uuid,status_input text) returns jsonb language plpgsql security definer set search_path=public as $$begin if not is_staff() then raise exception 'Forbidden';end if;if status_input not in ('ACTIVE','REVOKED') then raise exception 'Invalid status';end if;update tickets set status=status_input where id=ticket_id_input;return jsonb_build_object('message','Pass updated');end$$;
create function public.manage_certificate(user_id_input uuid,status_input text) returns jsonb language plpgsql security definer set search_path=public as $$begin if not is_staff() then raise exception 'Forbidden';end if;if status_input not in ('ISSUED','REVOKED') then raise exception 'Invalid status';end if;insert into certificates(user_id,recipient_name,status) select id,full_name,status_input from profiles where id=user_id_input on conflict(user_id) do update set status=excluded.status;return jsonb_build_object('message','Certificate updated');end$$;
create function public.verify_certificate(certificate_id uuid) returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('id',id,'recipient_name',recipient_name,'created_at',created_at,'status',status) from certificates where id=certificate_id and status='ISSUED'$$;
-- Restrict definer functions: internal award/profile helpers are never externally callable.
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on function is_staff(),is_admin() to anon,authenticated;
grant execute on function apply_forum(text,text,text,text),review_application(uuid,text),activate_promo(text),register_event(uuid),inspect_ticket(text),scan_ticket(text,uuid),adjust_coins(uuid,integer,text),generate_promos(integer,text,integer),manage_ticket(uuid,text),manage_certificate(uuid,text) to authenticated;
grant execute on function verify_certificate(uuid) to anon,authenticated;
-- Storage assets: organizers upload; published images are readable. No private ticket data belongs here.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('forum-assets','forum-assets',true,5242880,array['image/jpeg','image/png','image/webp','image/svg+xml']) on conflict do nothing;
create policy read_forum_assets on storage.objects for select using(bucket_id='forum-assets');
create policy staff_upload_assets on storage.objects for insert to authenticated with check(bucket_id='forum-assets' and public.is_staff());
create policy staff_update_assets on storage.objects for update to authenticated using(bucket_id='forum-assets' and public.is_staff()) with check(bucket_id='forum-assets' and public.is_staff());
create policy staff_delete_assets on storage.objects for delete to authenticated using(bucket_id='forum-assets' and public.is_staff());


-- supabase/migrations/202609070002_rewards.sql
-- Link sessions to configurable reward rules. NULL allows a custom per-event amount.
alter table events add column reward_rule_key text references coin_rules(key);
create function public.refresh_rule_events() returns trigger language plpgsql security definer set search_path=public as $$begin update events set coins=case when new.active then new.points else 0 end where reward_rule_key=new.key;return new;end$$;
create trigger refresh_rule_events after update of points,active on coin_rules for each row execute function refresh_rule_events();
create function public.apply_event_rule() returns trigger language plpgsql security definer set search_path=public as $$begin if new.reward_rule_key is not null then select case when active then points else 0 end into new.coins from coin_rules where key=new.reward_rule_key;end if;return new;end$$;
create trigger apply_event_rule before insert or update of reward_rule_key on events for each row execute function apply_event_rule();
create function public.competition_reward() returns trigger language plpgsql security definer set search_path=public as $$declare slug_value text;rule_key text;points integer;begin if new.status in ('FINALIST','FINAL','WINNER') then select slug into slug_value from competitions where id=new.competition_id;rule_key:=case slug_value when 'startup-battle' then 'startup_finalist' when 'hackathon' then 'hackathon' when 'jas-startuper' then 'jas_startuper' when 'fifa' then 'fifa' else null end;select r.points into points from coin_rules r where r.key=rule_key and active;perform award(new.user_id,coalesce(points,0),'Competition participation: '||slug_value,'competition:'||new.competition_id::text);end if;return new;end$$;
create trigger competition_reward after update of status on competition_entries for each row execute function competition_reward();
create function public.refresh_certificates() returns trigger language plpgsql security definer set search_path=public as $$declare uid uuid;begin if new.key='certificateThreshold' then if jsonb_typeof(new.value)<>'number' or (new.value::text)::integer<1 then raise exception 'Certificate target must be a positive integer';end if;for uid in select id from profiles loop perform sync_rewards(uid);end loop;end if;return new;end$$;
create trigger refresh_certificates after update of value on site_settings for each row execute function refresh_certificates();
revoke execute on function refresh_rule_events(),apply_event_rule(),competition_reward(),refresh_certificates() from public,anon,authenticated;


-- supabase/migrations/202609070003_capacity.sql
create function public.event_availability() returns table(event_id uuid,available integer) language sql stable security definer set search_path=public as $$select e.id,case when e.capacity is null then null else greatest(0,e.capacity-(select count(*)::integer from event_registrations r where r.event_id=e.id and r.status in ('REGISTERED','ATTENDED'))) end from events e where e.published$$;
revoke execute on function event_availability() from public;
grant execute on function event_availability() to anon,authenticated;


-- supabase/migrations/202609070004_password_admin_bootstrap.sql
create or replace function public.new_profile() returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into profiles(id,email,role)
  values(
    new.id,
    coalesce(new.email,''),
    case
      when lower(coalesce(new.email,'')) = 'amantaibatyrkhan11@gmail.com' then 'ADMIN'
      else 'USER'
    end
  );
  return new;
end
$$;

update public.profiles
set role = 'ADMIN'
where lower(email) = 'amantaibatyrkhan11@gmail.com';


-- supabase/seed.sql
-- Generated from lib/config.ts. No fabricated people or partners.
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000012','Opening of Digital Apta','The first connection. Meet the community and start a week of building.',12,'TBA','DIGITAL APTA','Venue TBA',null,false,20) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000013','Startup acceleration','12–18 September: mentoring, business models, pitch decks and preparation for Startup Battle.',12,'TBA','STARTUPS','Venue TBA',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000015','Vibe Coding','AI-assisted coding, rapid prototyping and turning an idea into an MVP. A one-hour workshop for hackathon teams.',15,'TBA','HACKATHON','Digital Lab',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000025','Startup Commercialization','Customer problems, value proposition, B2B / B2C / B2G, monetization and your first customers. Approximately one hour.',15,'TBA','STARTUPS','Venue TBA',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000016','Pitch Deck & Pitching','Problem, solution, market, product, business model, traction, competition, team and ask. Practice storytelling, timing and jury questions.',16,'TBA','WORKSHOPS','Main Stage',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000017','3D Modeling & 3D Printing','A practical workshop for NIS teachers: modeling, slicing and live printing. Create a simple model and explore classroom applications.',17,'TBA','3D','3D Lab',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000027','Finalists Reveal','Meet the selected teams and participants of all four competitions.',17,'TBA','DIGITAL APTA','Online',null,false,0) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000018','Mock Pitching','One day before the forum. Rehearse your pitch, answer questions and refine your presentation with expert feedback.',18,'TBA','STARTUPS','Main Stage',null,true,50) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000031','Session 01 · Secret Speaker','Topic to be revealed.',19,'TBA','MAIN STAGE','Main Stage',null,true,30) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000032','Session 02 · Secret Speaker','Topic to be revealed.',19,'TBA','MAIN STAGE','Main Stage',null,true,30) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000033','Session 03 · Secret Speaker','Topic to be revealed.',19,'TBA','MAIN STAGE','Main Stage',null,true,30) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000019','Panel Discussion','Three minds. One conversation. Your questions. Meet three independent panelists and join the Q&A.',19,'TBA','MAIN STAGE','Main Stage',null,true,40) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000029','Startup Battle · The Final','Eight startups. One stage. Discover ideas ready for their next chapter.',19,'TBA','STARTUPS','Main Stage',null,true,30) on conflict(id) do nothing;
insert into events(id,title,description,day,time,track,location,capacity,registration_required,coins) values('00000000-0000-4000-8000-000000000039','FIFA League · The Final','The final rounds and championship match. Tournament rules and timing to be announced.',19,'TBA','GAMING','Guest Area',null,true,80) on conflict(id) do nothing;
insert into competitions(id,slug,title,description) values('10000000-0000-4000-8000-000000000001','startup-battle','STARTUP BATTLE','8 startups. One stage. Bring your idea into the spotlight.') on conflict(slug) do nothing;
insert into competitions(id,slug,title,description) values('10000000-0000-4000-8000-000000000002','hackathon','NIS EDUTECH HACKATHON','Real challenges. Bold solutions. Build something that changes how we learn.') on conflict(slug) do nothing;
insert into competitions(id,slug,title,description) values('10000000-0000-4000-8000-000000000003','jas-startuper','JAS STARTUPER','A first stage for the next generation of founders and creators.') on conflict(slug) do nothing;
insert into competitions(id,slug,title,description) values('10000000-0000-4000-8000-000000000004','fifa','FIFA LEAGUE','Bring your skill. Find your team. Play for the final.') on conflict(slug) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000001','Main Stage','Big ideas, speaker sessions and the panel discussion.','01',0) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000002','Startup Battle','Meet the eight startup finalists and their ideas.','02',1) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000003','Hackathon Zone','Where teams build the future of education.','03',2) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000004','3D Lab','From a digital model to something you can hold.','04',3) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000005','Digital Lab','Explore technology through live demonstrations.','05',4) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000006','Registration','Scan your Digital Pass and collect your wristband.','06',5) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000007','Networking & Relax','Make a connection. Start a conversation. Recharge.','07',6) on conflict(id) do nothing;
insert into zones(id,name,description,icon,sort_order) values('20000000-0000-4000-8000-000000000008','Guest Area','A dedicated space for guests, participants and partners.','08',7) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000001',true,'KEYNOTE','SECRET SPEAKER 01',1) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000002',true,'KEYNOTE','SECRET SPEAKER 02',2) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000003',true,'KEYNOTE','SECRET SPEAKER 03',3) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000004',true,'PANELIST','PANELIST 01',4) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000005',true,'PANELIST','PANELIST 02',5) on conflict(id) do nothing;
insert into speakers(id,secret,kind,name,sort_order) values('30000000-0000-4000-8000-000000000006',true,'PANELIST','PANELIST 03',6) on conflict(id) do nothing;
insert into coin_rules(key,name,points) values('registration','Forum registration',20) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('check_in','Forum check-in',50) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('masterclass','Masterclass attendance',50) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('speaker','Speaker session',30) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('panel','Panel discussion',40) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('startup_audience','Startup Battle audience',30) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('hackathon','Hackathon participant',100) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('startup_finalist','Startup Battle finalist',150) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('jas_startuper','Jas Startuper participant',100) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('fifa','FIFA League participant',80) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('3d','3D workshop',50) on conflict(key) do nothing;
insert into coin_rules(key,name,points) values('special','Special activity',20) on conflict(key) do nothing;
insert into achievements(key,name,description) values('FIRST_STEP','FIRST STEP','Registration completed') on conflict(key) do nothing;
insert into achievements(key,name,description) values('DIGITAL_EXPLORER','DIGITAL EXPLORER','Visit 3 sessions') on conflict(key) do nothing;
insert into achievements(key,name,description) values('BUILDER','BUILDER','Attend a workshop') on conflict(key) do nothing;
insert into achievements(key,name,description) values('NETWORKER','NETWORKER','Participate in the panel') on conflict(key) do nothing;
insert into achievements(key,name,description) values('STARTUP_MIND','STARTUP MIND','Attend Startup Battle') on conflict(key) do nothing;
insert into achievements(key,name,description) values('DIGITAL_MASTER','DIGITAL MASTER','Reach the certificate target') on conflict(key) do nothing;
insert into site_settings(key,value) values('certificateThreshold','400'),('registrationEnabled','true'),('finalists_published','false'),('announcement','""') on conflict(key) do nothing;

update events set reward_rule_key=case when title='Panel Discussion' then 'panel' when title like 'Session %' then 'speaker' when title like 'Startup Battle%' then 'startup_audience' when track='3D' then '3d' when track='GAMING' then 'fifa' when track in ('WORKSHOPS','HACKATHON') or title in ('Startup Commercialization','Mock Pitching','Startup acceleration') then 'masterclass' else null end;

commit;
