-- Link sessions to configurable reward rules. NULL allows a custom per-event amount.
alter table events add column reward_rule_key text references coin_rules(key);
create function public.refresh_rule_events() returns trigger language plpgsql security definer set search_path=public as $$begin update events set coins=case when new.active then new.points else 0 end where reward_rule_key=new.key;return new;end$$;
create trigger refresh_rule_events after update of points,active on coin_rules for each row execute function refresh_rule_events();
create function public.apply_event_rule() returns trigger language plpgsql security definer set search_path=public as $$begin if new.reward_rule_key is not null then select case when active then points else 0 end into new.coins from coin_rules where key=new.reward_rule_key;end if;return new;end$$;
create trigger apply_event_rule before insert or update of reward_rule_key on events for each row execute function apply_event_rule();
create function public.competition_reward() returns trigger language plpgsql security definer set search_path=public as $$declare slug_value text;rule_key text;points integer;begin if new.status in ('FINALIST','FINAL','WINNER') then select slug into slug_value from competitions where id=new.competition_id;rule_key:=case slug_value when 'startup-battle' then 'startup_finalist' when 'hackathon' then 'hackathon' when 'fifa' then 'fifa' else null end;select r.points into points from coin_rules r where r.key=rule_key and active;perform award(new.user_id,coalesce(points,0),'Competition participation: '||slug_value,'competition:'||new.competition_id::text);end if;return new;end$$;
create trigger competition_reward after update of status on competition_entries for each row execute function competition_reward();
create function public.refresh_certificates() returns trigger language plpgsql security definer set search_path=public as $$declare uid uuid;begin if new.key='certificateThreshold' then if jsonb_typeof(new.value)<>'number' or (new.value::text)::integer<1 then raise exception 'Certificate target must be a positive integer';end if;for uid in select id from profiles loop perform sync_rewards(uid);end loop;end if;return new;end$$;
create trigger refresh_certificates after update of value on site_settings for each row execute function refresh_certificates();
revoke execute on function refresh_rule_events(),apply_event_rule(),competition_reward(),refresh_certificates() from public,anon,authenticated;
